version: '3'
networks:
  poolnet:

services:
  db:
    container_name: pool-db
    image: postgres:13.1-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file: ./apps/api/.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - poolnet

  db-admin:
    profiles: ["dev"]
    container_name: pool-db-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pool@codephobia.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - poolnet

  api:
    container_name: pool-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    image: pool-api:0.1.0
    restart: always
    env_file: ./apps/api/.env
    environment:
      POSTGRES_HOST: db
    ports:
      - 1268:1268
    networks:
      - poolnet
    depends_on:
      - db
    volumes:
      - ./apps/api:/workspace/apps/api
      - ./libs/go:/workspace/libs/go

  overlay:
    container_name: pool-overlay
    build:
      context: .
      dockerfile: ./apps/overlay/Dockerfile
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    image: pool-overlay:0.1.0
    ports:
      - 4200:4200
    command: npx nx serve overlay -- --host 0.0.0.0 --disableHostCheck --poll 1
    volumes:
      - ./apps/overlay:/workspace/apps/overlay
      - ./libs:/workspace/libs
    networks:
      - poolnet
    depends_on:
      - api

  dashboard:
    container_name: pool-dashboard
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    image: pool-dashboard:0.1.0
    ports:
      - 4201:4200
    command: npx nx serve dashboard -- --host 0.0.0.0 --disableHostCheck --poll 1
    volumes:
      - ./apps/dashboard:/workspace/apps/dashboard
      - ./libs:/workspace/libs
    networks:
      - poolnet
    depends_on:
      - api
  telestrator:
    container_name: pool-telestrator
    build:
      context: .
      dockerfile: ./apps/telestrator/Dockerfile
      args:
        FONTAWESOME_NPM_AUTH_TOKEN: ${FONTAWESOME_NPM_AUTH_TOKEN}
    image: pool-telestrator:0.1.0
    ports:
      - 4202:4200
    command: npx nx serve telestrator -- --host 0.0.0.0 --disableHostCheck --poll 1
    volumes:
      - ./apps/telestrator:/workspace/apps/telestrator
      - ./libs:/workspace/libs
    networks:
      - poolnet
    depends_on:
      - api
volumes:
  postgres:
  pgadmin:
