name: Lint Go

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  run-linter:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
